import React, { useEffect, useState } from 'react'
import StatCard from '../components/StatCard'
import { api } from '../utils/api'

export default function Dashboard() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    let mounted = true
    setLoading(true)
    api.get('/dashboard').then((res) => {
      if (!mounted) return
      setData(res.data)
    }).catch(() => {
      // fallback demo
      setData({ total: 124, avgFit: 74, diversity: 0.68, referrals: 12 })
    }).finally(() => setLoading(false))
    return () => { mounted = false }
  }, [])

  const skeleton = (w = 40) => <div className="h-6 bg-slate-100 rounded" style={{ width: w }} />

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <StatCard title="Total Candidates" value={loading ? skeleton() : data?.total} data={[{v:10},{v:12},{v:8}]} />
        <StatCard title="Avg Fit Score" value={loading ? skeleton() : `${data?.avgFit}%`} data={[{v:6},{v:14},{v:9}]} />
        <StatCard title="Diversity Index" value={loading ? skeleton() : data?.diversity} data={[{v:3},{v:5},{v:2}]} />
        <StatCard title="Referrals" value={loading ? skeleton() : data?.referrals} data={[{v:2},{v:3},{v:4}]} />
      </div>

      <div className="p-4 bg-white rounded-2xl card-shadow">
        <div className="flex items-center justify-between">
          <div className="font-semibold">AI Summaries</div>
          <div className="flex items-center gap-2">
            <select className="p-2 border rounded-md text-sm">
              <option>All roles</option>
            </select>
          </div>
        </div>
        <div className="mt-4 text-sm text-slate-600">Summaries generated by AI appear here. Use filters to refine results.</div>
      </div>
    </div>
  )
}
